### Test TradingView Alert Webhook
POST https://jtfx-algo-108173118287.herokuapp.com/webhook
Content-Type: application/json

{
  "signal": "BUY",
  "ticker": "TestingSignalJPY",
  "price": 145.235,
  "tp_pips": 75,
  "sl_pips": 150.00
}
