### Test TradingView Alert Webhook
POST https://jtfx-algo-108173118287.herokuapp.com/webhook
Content-Type: application/json

{
  "symbol": "BTCUSD",
  "price": "67000",
  "time": "2025-04-15T12:34:56Z",
  "signal": "Buy"
}
